// Genre images mapping - all images should be placed in public/assets/genres/
export const GENRE_IMAGES: Record<string, string> = {
	pop: "/assets/genres/pop.jpg",
	rock: "/assets/genres/rock.jpg",
	jazz: "/assets/genres/jazz.jpg",
	classical: "/assets/genres/classical.jpg",
	electronic: "/assets/genres/electronic.jpg",
	hiphop: "/assets/genres/hiphop.jpg",
	news: "/assets/genres/news.jpg",
	talk: "/assets/genres/talk.jpg",
	ambient: "/assets/genres/ambient.jpg",
	country: "/assets/genres/country.jpg",
	latin: "/assets/genres/latin.jpg",
	metal: "/assets/genres/metal.jpg",
	blues: "/assets/genres/blues.jpg",
	reggae: "/assets/genres/reggae.jpg",
	folk: "/assets/genres/folk.jpg",
	indie: "/assets/genres/indie.jpg",
	soul: "/assets/genres/soul.jpg",
	funk: "/assets/genres/funk.jpg",
	disco: "/assets/genres/disco.jpg",
	house: "/assets/genres/house.jpg",
	techno: "/assets/genres/techno.jpg",
	trance: "/assets/genres/trance.jpg",
	dubstep: "/assets/genres/dubstep.jpg",
	rnb: "/assets/genres/rnb.jpg",
	punk: "/assets/genres/punk.jpg",
	gospel: "/assets/genres/gospel.jpg",
	world: "/assets/genres/world.jpg",
	alternative: "/assets/genres/alternative.jpg",
};

export const DEFAULT_GENRE_IMAGE = "/assets/genres/default.jpg";
